# .github/label-commenter-config.yml

labels:
  # 等待完成自检
  - name: waiting checklist
    labeled:
      issue:
        body: |
          :wave: Hello,
          请按照模板中的操作步骤进行自检，然后告诉我们您的操作结果，这将有助于我们协助您解决问题。
          Please follow the steps in the issue template for self-check, and then tell us the result of your operation, which will help us to help you solve the problem.
  # 需要更多信息
  - name: need more info
    labeled:
      issue:
        body: |
          :wave: Hello,
          我们需要更多信息才能给出建议，请重新编辑您的 issue ，完善模板中要求提供的信息，并尽可能详细地描述您的问题。
          We need more information to make suggestions. Please edit your issue again, complete the information requested in the template, and describe your issue in as much detail as possible.
  # 请描述详细一点
  - name: describe in detail
    labeled:
      issue:
        body: |
          :wave: Hello,
          请尽可能详细地描述您的问题。如果不知道如何详细地描述问题，这份教程可以帮助您：[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md) 。
          Please describe your problem in as much detail as possible. If you don’t know how to describe the problem in detail, this article can help you: [How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html).
  # 文档中有答案
  - name: read docs
    labeled:
      issue:
        body: |
          :wave: Hello,
          您的疑问在 [Volantis](https://volantis.js.org) 和 [Hexo](https://hexo.io) 的官方文档有答案，如果找不到可以尝试进行搜索。
          Your question is answered in the official documents of [Volantis](https://volantis.js.org) and [Hexo](https://hexo.io), if you can’t find it, you can try to search.
  # 采纳的建议
  - name: intend
    labeled:
      issue:
        body: |
          :wave: Hello,
          您的建议已经在计划中了，非常感谢！
          Your suggestion is already in the plan, thank you very much!

  # 迟迟没有回复
  - name: waiting feedback
    labeled:
      issue:
        body: |
          :wave: Hello,
          您好，还在吗？我们正等待您的回应，如果您迟迟不予回复，我们将会关闭这个 issue 。
          Hello, are you still there? We are waiting for your response. If you do not reply, we will close this issue.

  ################ 关闭 ################
  # 重复的问题
  - name: duplicate
    labeled:
      issue:
        body: |
          :wave: Hello,
          这是一个重复的问题，但我们仍然感谢您的反馈。
          This is a duplicate issue, but we still appreciate your feedback.
        action: close
  # 不予修复
  - name: wontfix
    labeled:
      issue:
        body: |
          :wave: Hello,
          由于设计如此，或者是外界问题，这将无法进行，但我们感谢您的贡献。
          Because of the design, or external problems, this will not be worked on but we appreciate your contribution.
        action: close
  # 由于没有回复而被关闭
  - name: losing contact
    labeled:
      issue:
        body: |
          :wave: Hello,
          由于您迟迟不予回复，我们关闭了这个 issue 。
          Due to your delay in replying, we closed this issue.
        action: close
  # 问题得以解决
  - name: resolved
    labeled:
      issue:
        body: |
          :wave: Hello,
          此 issue 已经被解决。
          This issue has been resolved.
        action: close
  # BUG得以修复
  - name: fixed
    labeled:
      issue:
        body: |
          :wave: Hello,
          此 BUG 已经被修复。
          This BUG has been fixed.
        action: close
