##########################################################################
############################## 主题基本信息 ################################
theme_info:
  name: Material X
  version: 1.0-beta10
  docs: https://xaoxuu.com/wiki/material-x/
  # 主题的CDN地址，如果你的源码托管到国内CDN可以更改此链接。如需启用CDN，请在主目录的config中设置import，详见文档。
  cdn: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@18.12.29/
##########################################################################
# 请务必阅读官方文档！！！
# 请务必阅读官方文档！！！
# 请务必阅读官方文档！！！


# style: material    # 导航栏和标题栏背景是主题色
style: pure        # 导航栏和标题栏背景是白色


# 右边的小窗口，不想显示哪一项的把enable设置为false即可
widgets:
  # 博主信息区，是否显示个人头像、格言、社交信息等
  author:
    enable: true
    avatar: true # 是否显示头像，如果是，需要在主目录的config中写avatar的URL
    title: true # 是否显示博客名、头衔等等。如果是，需要在主目录的config中写title
    motto: true # 是否显示格言座右铭等等。如果是，需要在主目录的config中写motto
    social: true # 是否显示社交信息（内容同页脚的社交信息）如果是，需要在主目录的config中写social，支持icon和URL
  # 显示文章分类
  categories:
    enable: true
    icon: fas fa-folder-open
    title: "博文分类"
  # 显示文章标签
  tagcloud:
    enable: true
    icon: fas fa-tags
    title: "热门话题"
  # 显示音乐播放器
  music:
    enable: true
    display:           # 批量控制哪一类页面显示
      home: false      # 在主页是否显示
      tag: false       # 在标签页面是否显示
      category: false  # 在分类页面是否显示
      archive: false   # 在归档页面是否显示
      page: false      # layout: page 的页面是否显示
      links: true      # layout: links 的页面是否显示
      post: true       # layout: post 的页面是否显示
    icon: fas fa-compact-disc
    title: "最近在听"
    link: 'https://music.163.com/#/user/home?id=63035382'
    color: '#3DC550'  # 主题色
    volume: 0.5       # 默认音量大小（0~1之间）
    mode: circulation # random （随机） single （单曲） circulation （列表循环） order （列表）
    server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
    type: playlist    # song （单曲） album （专辑） playlist （歌单） search （搜索）
    id: 746319661     # 歌曲/专辑/歌单 ID
  # 显示友链，友链的内容写在主目录的config中
  links:
    enable: false
    icon: fas fa-handshake
    title: "友链"
    mailto: "me@xaoxuu.com" # 右边显示➕ ，点击给这个地址发送邮件添加友链
  # 显示目录（在文章中设置toc:false可以隐藏单篇文章的目录）
  toc:
    enable: true
    icon: fas fa-list
    title: "目录"


# 推荐文章
recommended_posts:
  autoDisplay: false # 自动在文章底部显示推荐文章，如果你使用Material-X主题，这里要设置为false。
  server: https://api.truelaurel.com # 后端推荐服务器地址
  timeoutInMillis: 10000 # 服务时长，超过此时长，则使用离线推荐模式
  excludePattern: []
  titleHtml: <h4>推荐文章</h4> #自定义标题
  internalLinks: 3 # 内部文章数量
  externalLinks: 2 # 外部文章数量
  fixedNumber: false


# Search
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less
less:
  compress: true
