# Search
search:
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:

# navigation menu
menu:
  - name: 主页
    slug: about
    fa:   home
    url: https://xaoxuu.com
  - name: 博客
    slug: home
    fa:   rss
    url: /
  - name: 归档
    slug: archives
    fa:   archive
    url: /archives
  - name: 项目
    slug: projects
    fa:   cube
    url: https://xaoxuu.com/proj


# widgets
widgets:
  - about
  - categories
  - tagcloud
  # - socials
  # - music

# Less
less:
  compress: true



# use url, not username
social:
- slug: envelope
  url: mailto:me@xaoxuu.com
- slug: github
  url: https://github.com/xaoxuu
- slug: instagram
  url: https://www.instagram.com/xaoxuu
- slug: google-plus
  url: https://plus.google.com/u/0/105328339611794285997
- slug: twitter
  url: https://twitter.com/xaoxuu
- slug: music
  url: https://music.163.com/#/user/home?id=63035382




contacts:
- name: Email
  badget: me@xaoxuu.com
  url: mailto:me@xaoxuu.com
- name: GitHub
  badget: "@xaoxuu"
  url: https://github.com/xaoxuu
# - name: Instagram
#   badget: "@xaoxuu"
#   url: https://www.instagram.com/xaoxuu
# - name: Twitter
#   badget: "@xaoxuu"
#   url: https://www.twitter.com/xaoxuu
