# 导航栏

menu:
- name: 主页
  slug: about
  fa:   home
  url: https://xaoxuu.com
- name: 项目
  slug: projects
  fa:   cube
  url: https://xaoxuu.com/proj
- name: 博客
  slug: home
  fa:   rss
  url: /
- name: 归档
  slug: archives
  fa:   archive
  url: /archives

# 右边的小窗口
widgets:
  - avatar # 显示个人头像，如果注释掉这一行就不显示
  - categories # 显示分类
  - tagcloud # 显示tags
  - contacts # 显示自己的联系信息
  - music # 显示自己的网易云歌单
  - links # 显示友链


# 页面底部的社交信息
social:
- slug: envelope
  url: mailto:me@xaoxuu.com
- slug: github
  url: https://github.com/xaoxuu
- slug: instagram
  url: https://www.instagram.com/xaoxuu
- slug: google-plus
  url:
- slug: twitter
  url: https://twitter.com/xaoxuu
- slug: music
  url: https://music.163.com/#/user/home?id=63035382


# 推荐文章 npm install hexo-recommended-posts --save
recommended_posts:
  enabled: true

# Search
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:



# Less
less:
  compress: true
